# Generated by Django 5.2.5 on 2025-09-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StuId', models.IntegerField()),
                ('StuName', models.CharField(max_length=30)),
                ('StuMarks', models.IntegerField()),
            ],
        ),
    ]
