# Generated by Django 5.2.5 on 2025-09-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='StuId',
            field=models.IntegerField(verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='StuName',
            field=models.CharField(max_length=30, verbose_name='Student Name'),
        ),
    ]
