# Generated by Django 5.2.5 on 2025-09-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eid', models.IntegerField()),
                ('Ename', models.CharField(max_length=30)),
                ('Esal', models.FloatField()),
            ],
        ),
    ]
