# Generated by Django 5.2.5 on 2025-11-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuname', models.CharField(max_length=40)),
                ('stuage', models.IntegerField()),
                ('stuqual', models.CharField(max_length=40)),
                ('stuemail', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
