# Generated by Django 5.2.5 on 2025-09-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empId', models.IntegerField()),
                ('empName', models.CharField(max_length=30)),
                ('empSal', models.FloatField()),
                ('empDept', models.CharField(max_length=30)),
            ],
        ),
    ]
