# Generated by Django 5.2.5 on 2025-12-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('ename', models.CharField(max_length=20)),
                ('esal', models.IntegerField()),
                ('eimage', models.ImageField(upload_to='')),
            ],
        ),
    ]
