# Generated by Django 5.2.5 on 2025-09-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuId', models.IntegerField()),
                ('stuName', models.CharField(max_length=30)),
                ('stuMarks', models.IntegerField()),
            ],
        ),
    ]
